### ISSUE TITLE
大神请问最后的输出层(clf)是如何进行比较的呢？

### ISSUE THREAD

**Issue by xiaobingbuhuitou** [wutong8023/PLM4CL#3]
在layer_probing中您使用prob_features进行解析每一层所有类别的proto，然后通过prob_proto_classify将proto和对应的层提取的特征求解logits从而预测，这边走过了所有的transformer层，但是我并没有找到最后的输出linear是如何对比出遗忘的？请指教。谢谢了

**Comment by wutong8023** [comment]
中间层的输入是hidden state, clf的输出是logits, 对它求prototype没有意义，直接根据logits分类就好了
